# This file allows you to configure the Dart analyzer.
#
# The commented part below is just for inspiration. Read the guide here:
#   https://www.dartlang.org/guides/language/analysis-options

include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/issues/**

linter:
  rules:
    - use_string_in_part_of_directives: false
    - unnecessary_library_name: false

